# Generated by Django 3.2 on 2021-05-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ROI',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
