# Generated by Django 3.2 on 2021-05-14 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210513_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_fighter_name', models.CharField(blank='False', max_length=255)),
                ('blue_fighter_name', models.CharField(blank='False', max_length=255)),
                ('red_fighter_odds', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('blue_fighter_odds', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('prediction_made', models.BooleanField(default=True)),
                ('red_fighter_pred', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('blue_fighter_pred', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('expected_return', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ROI', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('winner', models.IntegerField(blank='False')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='events.event')),
            ],
        ),
    ]
