# Generated by Django 3.2 on 2021-05-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_fight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='winner',
            field=models.IntegerField(blank='True'),
        ),
    ]
