# Generated by Django 3.2 on 2021-05-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_fight_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='winner',
            field=models.IntegerField(blank='True', default='null'),
        ),
    ]
