# Generated by Django 3.2 on 2021-05-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_fight_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fight',
            old_name='event_id',
            new_name='event',
        ),
    ]
