# Generated by Django 3.2 on 2021-05-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_event_id_fight_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='prediction_made',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fight',
            name='winner',
            field=models.IntegerField(blank=True, default='null'),
        ),
    ]
