# Generated by Django 3.2 on 2021-05-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210514_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='winner',
            field=models.IntegerField(blank=True),
        ),
    ]
