# Generated by Django 3.2 on 2021-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_fight_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='winner',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
