# Generated by Django 3.2 on 2021-05-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_fight_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='predicted_winner',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True),
        ),
    ]
